package com.yelun.weixin.repo.user;

import com.yelun.weixin.domain.user.wechatUser;
import com.yelun.weixin.domain.user.wechatUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface wechatUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    long countByExample(wechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int deleteByExample(wechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int insert(wechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int insertSelective(wechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    List<wechatUser> selectByExample(wechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    wechatUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") wechatUser record, @Param("example") wechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") wechatUser record, @Param("example") wechatUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(wechatUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wechat_user
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(wechatUser record);
}